author: "Jérôme Sautret <jerome.sautret at process-one.net>"
category: "log"
summary: "Logging chat messages in text files"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
