author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "muc"
summary: "Auto-bookmark rooms on registration"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
