author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "log"
summary: "Log one line per message transmission in text file"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
