author: "Igor Goryachev <igor at goryachev.org>"
category: "data"
summary: "Publish user presence information in the web"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
