author: "Tom Quackenbush <tom at madglory.com>"
category: "data"
summary: "Filter bad words in messages"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
