author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "policy"
summary: "Prevent OMEMO sessions from being established"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
