author: "Badlop <badlop at process-one.net>"
category: "stats"
summary: "Observer CLI plugins for ejabberd"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
