author: "Badlop <badlop at process-one.net>"
category: "log"
summary: "Serve MUC logs on the web"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
