author: "Badlop <badlop at process-one.net>"
category: "admin"
summary: "Execute scheduled commands"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
