author: "Magnus Henoch <henoch@dtek.chalmers.se>"
category: "data"
summary: "Flexible filtering by server policy"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
