author: "Evgeny Khramtsov <ekhramtsov at process-one.net>"
category: "policy"
summary: "Prevent routing of packets between virtual hosts"
home: "https://github.com/ftntming/ejabberd-contrib2/tree/master/"
url: "git@github.com:ftntming/ejabberd-contrib2.git"
